Repository ipython/traitlets, pull requests merged in 2022-12, with the labels that each got.

#810 Minor fixes for Application.aliases
  traitlets/config/application.py
  traitlets/config/loader.py
  traitlets/config/tests/test_application.py
Labels: maintenance

#809 Adopt ruff and address lint
  .github/dependabot.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  docs/sphinxext/github.py
  pyproject.toml
  traitlets/config/application.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/config/tests/test_application.py
  traitlets/config/tests/test_configurable.py
  traitlets/config/tests/test_loader.py
  traitlets/tests/test_traitlets.py
  traitlets/tests/test_traitlets_enum.py
  traitlets/tests/utils.py
  traitlets/traitlets.py
  traitlets/utils/bunch.py
  traitlets/utils/getargspec.py
  traitlets/utils/importstring.py
Labels: maintenance

#777 Performance: decrease runtime overhead for constructing HasTraits (up to 20x faster)
  traitlets/tests/test_traitlets.py
  traitlets/traitlets.py
Labels: enhancement

#814 Fix lint
  .pre-commit-config.yaml
  pyproject.toml
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/tests/test_traitlets_enum.py
  traitlets/utils/getargspec.py
Labels: maintenance

#816 define trait.__doc__ = trait.help
  traitlets/traitlets.py
Labels: enhancement

#817 Expose more attributes for typing
  .pre-commit-config.yaml
  pyproject.toml
  traitlets/__init__.py
  traitlets/config/__init__.py
  traitlets/tests/test_traitlets.py
Labels: maintenance

#811 Initial support for argcomplete for KVArgParseConfigLoader
  docs/readme-docs.md
  docs/source/config.rst
  examples/argcomplete_app.py
  examples/docs/aliases.py
  examples/docs/configs/base_config.py
  examples/docs/configs/main_config.py
  examples/docs/container.py
  examples/docs/flags.py
  examples/docs/from_string.py
  examples/docs/load_config_app.py
  examples/docs/multiple_apps.py
  examples/docs/subcommands.py
  examples/myapp.py
  examples/subcommands_app.py
  pyproject.toml
  traitlets/config/application.py
  traitlets/config/argcomplete_config.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/config/tests/test_argcomplete.py
  traitlets/traitlets.py
  traitlets/utils/__init__.py
Labels: enhancement, documentation

#821 Add more api docs
  docs/source/config-api.rst
Labels: documentation
