Repository ipython/traitlets, pull requests merged in 2023-09, with the labels that each got.

#858 rename `MyClass` to `School`
  docs/source/config.rst
  examples/docs/configs/base_config.py
  examples/docs/configs/main_config.py
  examples/docs/load_config_app.py
Labels: documentation

#855 Even though returning a value from a validation method is ideal, by no means is `proposal['value']` the only thing that can be returned
  docs/source/using_traitlets.rst
Labels: documentation

#818 feat: trait typing
  docs/source/conf.py
  examples/docs/from_string.py
  examples/myapp.py
  pyproject.toml
  traitlets/config/application.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/tests/test_traitlets.py
  traitlets/tests/test_typing.py
  traitlets/traitlets.py
Labels: enhancement

#868 Typing upgrades
  traitlets/config/application.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/log.py
  traitlets/tests/test_typing.py
  traitlets/traitlets.py
  traitlets/utils/importstring.py
  traitlets/utils/sentinel.py
  traitlets/utils/tests/test_importstring.py
  traitlets/utils/warnings.py
Labels: maintenance
