Repository ipython/traitlets, pull requests merged in 2023-01, with the labels that each got.

#824 fix: mro_trait can be unbound when the class is not in mro
  traitlets/traitlets.py
Labels: bug

#829 Polishing argcomplete support
  traitlets/config/application.py
  traitlets/config/argcomplete_config.py
  traitlets/config/loader.py
  traitlets/config/tests/test_application.py
  traitlets/config/tests/test_argcomplete.py
Labels: enhancement

#826 Test that name and description can be set via constructor.
  traitlets/config/tests/test_application.py
Labels: maintenance
