Repository ipython/traitlets, pull requests merged in 2023-10, with the labels that each got.

#873 More Typing Adoption
  pyproject.toml
  tests/__init__.py
  tests/_warnings.py
  tests/config/__init__.py
  tests/config/test_application.py
  tests/config/test_argcomplete.py
  tests/config/test_configurable.py
  tests/config/test_loader.py
  tests/test_traitlets.py
  tests/test_traitlets_docstring.py
  tests/test_traitlets_enum.py
  tests/test_typing.py
  tests/utils/__init__.py
  tests/utils/test_bunch.py
  tests/utils/test_decorators.py
  tests/utils/test_importstring.py
  traitlets/__init__.py
  traitlets/config/application.py
  traitlets/config/argcomplete_config.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/config/manager.py
  traitlets/config/sphinxdoc.py
  traitlets/log.py
  traitlets/tests/test_traitlets.py
  traitlets/tests/utils.py
  traitlets/traitlets.py
  traitlets/utils/__init__.py
  traitlets/utils/bunch.py
  traitlets/utils/decorators.py
  traitlets/utils/descriptions.py
  traitlets/utils/getargspec.py
  traitlets/utils/nested_update.py
  traitlets/utils/text.py
Labels: maintenance

#875 Typing fixups
  traitlets/config/application.py
  traitlets/tests/utils.py
Labels: maintenance

#877 More typing cleanup
  traitlets/config/application.py
  traitlets/tests/utils.py
Labels: maintenance

#880 Fix docs version
  docs/source/conf.py
Labels: documentation, 5.0-no-incidence

#882 Cleanup after remove Python 2 support
  tests/config/test_application.py
Labels: maintenance

#881 Pass **kwds in MetaHasDescriptors __new__ and __init__
  traitlets/traitlets.py
Labels: enhancement

#879 Add more project URLs, trove classifiers
  pyproject.toml
Labels: maintenance

#883 Adopt sp-repo-review
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  CHANGELOG.md
  docs/source/api.rst
  docs/source/config.rst
  docs/source/migration.rst
  docs/source/using_traitlets.rst
  pyproject.toml
  tests/_warnings.py
  tests/config/test_application.py
  tests/config/test_loader.py
  tests/test_traitlets.py
  traitlets/config/application.py
  traitlets/config/argcomplete_config.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/tests/test_traitlets.py
  traitlets/traitlets.py
  traitlets/utils/__init__.py
  traitlets/utils/decorators.py
  traitlets/utils/descriptions.py
Labels: maintenance

#884 Use passed-in `info` argument for `TraitType.error()`
  traitlets/traitlets.py
Labels: bug

#885 Finish Strict Typing
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/source/conf.py
  examples/docs/configs/base_config.py
  examples/docs/configs/main_config.py
  pyproject.toml
  tests/config/test_application.py
  tests/config/test_argcomplete.py
  tests/test_typing.py
  traitlets/__init__.py
  traitlets/config/argcomplete_config.py
  traitlets/config/configurable.py
  traitlets/config/loader.py
  traitlets/config/sphinxdoc.py
  traitlets/traitlets.py
Labels: maintenance

#886 Improve generics handling
  tests/test_typing.py
  traitlets/config/application.py
  traitlets/config/loader.py
  traitlets/traitlets.py
Labels: maintenance
