Repository ipython/traitlets, pull requests merged in 2025-02, with the labels that each got.

#915 deprecate empty isidentifier utility
  traitlets/traitlets.py
Labels: maintenance

#912 suppress exceptions when closing handlers during `__del__`
  traitlets/config/application.py
Labels: bug

#917 Fix whitespace formatting in CLI help.
  traitlets/config/configurable.py
  traitlets/utils/text.py
Labels: enhancement

#913 avoid using `return t.cast` which can prevent attribute access during process teardown
  traitlets/traitlets.py
Labels: bug
